### ISSUE TITLE
Password protected posts included in query, but inaccessible

### ISSUE THREAD

**Issue by avidsapp** [henrikwirth/gatsby-starter-wordpress-twenty-twenty#12]
Password protected posts are included in the post query and displayed at the beginning of the search results. However, they are inaccessible and break the blog roll page.

On the blog roll page...

Error: `TypeError: Cannot read property 'uri' of undefined`

src/components/PostMeta.js:19
```
  16 | </span>
  17 | <span className="meta-text">
  18 |   By{" "}
> 19 |   <Link to={author.uri}>
  20 |     {author.firstName
  21 |       ? author.lastName
  22 |         ? author.firstName + " " + author.lastName
```

On the password protected posts after replacing the call to author object with arbitrary links and text...

Error: `TypeError: Cannot read property 'description' of undefined`

src/components/AuthorBio.js:7
```
   4 | 
   5 | const AuthorBio = ({ author }) => {
   6 |   author = author?.node
>  7 |   if (!author.description) return null
   8 | 
   9 |   const description = author.description.replace(/(\r\n|\n|\r)/gm, "<br/>")
  10 |
```

**Comment by henrikwirth** [comment]
@avidsapp it just seems that it doesn't find an Author at all. Maybe the author is not set on your post? If so, you can also put another conditional into it to make sure it doesn't error out. Obviously it won't render either if it doesn't have the author.

`!author?.description`

**Comment by henrikwirth** [comment]
Let me know if this hasn't been solved yet. Will close it for now though and reopen if needed.
