### ISSUE TITLE
wp-block-cover not functioning as expected

### ISSUE THREAD

**Issue by avidsapp** [henrikwirth/gatsby-starter-wordpress-twenty-twenty#20]
Possibly after upgrading from `gatsby-source-wordpress-experimental` to `gatsby-source-wordpress` v4, but now the `wp-block-cover` block is no longer functioning as expected. Before, the `background-image` was added to the div with class `wp-block-cover`, but now the `background-image` is added to an `<img>` and `<picture>` child of the div with class `wp-block-cover__image-background`, the background image does not cover the container, and the div with class `wp-block-cover__inner-container` is a sibling to the div with class `wp-block-cover__image-background` rather than a child, putting it below the background.

The difference can be seen at [https://yaaxche.org](yaaxche.org) (old, unchanged and cached) and [https://yaaxche.org/about-us/our-work/](yaaxche.org/about-us/our-work/) (new, updated content).

Old:
![Screen Shot 2021-03-23 at 7 59 08 PM](https://user-images.githubusercontent.com/11481762/112242940-53503f00-8c12-11eb-90af-af855c640c99.png)

Updated:
![Screen Shot 2021-03-23 at 8 01 03 PM](https://user-images.githubusercontent.com/11481762/112243100-9f02e880-8c12-11eb-83f3-41341fceb6d1.png)

Any ideas?

**Comment by henrikwirth** [comment]
Seems like the markup moved from background-image to an actual image. You will have to adjust your styling.

**Comment by henrikwirth** [comment]
Maybe they also updated it in the new twenty twenty theme. You might be able to find styling related to it here: https://themes.trac.wordpress.org/browser/twentytwenty/1.7/style.css?rev=144394

**Comment by avidsapp** [comment]
I was hoping there was an easier solution. I guess I'll bend the styling to my will in that case. Thanks.

**Comment by avidsapp** [comment]
The following code added to `style-php.css` resolves the issue. A `banner-background` class must be added to the cover block from the wp dashboard.

```
/* BLOCK COVER FIX */
.wp-block-cover.alignfull.has-background-dim.banner-background {
  padding: 0px !important;
}
.wp-block-cover.alignfull.has-background-dim.banner-background > .wp-block-cover__image-background {
  position: unset !important;
  overflow: visible !important;
}
.wp-block-cover.alignfull.has-background-dim.banner-background > .wp-block-cover__image-background > span {
  display: contents !important;
}
.wp-block-cover.alignfull.has-background-dim.banner-background > .wp-block-cover__image-background > picture > img {
  object-fit: cover !important;
}
```
