### ISSUE TITLE
I added Tags, they work, but I can't get them to render on posts

### ISSUE THREAD

**Issue by stevewil** [henrikwirth/gatsby-starter-wordpress-twenty-twenty#21]
First off, thank you for sharing some of your code you are developing for your thesis. Lately, I have been hacking a bunch of Gatsby github repos related to WordPress, and yours is literally the first plug-in-play code I've encountered with gatsby-source-wordpress 4.0. You made it incredibly simple to get started: I just added my WordPress url in gatsby-config and it was away we go.

Almost everything else I have encountered elsewhere is too dated for my low entry level so I always seem to get to a cul-de-sac of issues that have never been quite satisfactory for doing current Wordpress/Gatsby.

I wanted to let you all know that I was able to partially get Tags to work by simply taking the code you have for /src/components/PostCategories.js, copying it as /src/components/PostTags.js , then doing find-and-replace for "Categories"|"Tags", "categories"|"tags", "category|tag". I also added these new lines to gatsby-node.js to account for where the new file is located and its create runtime seqencing:

```const createTags = require(`./create/createTags`)```

and

```await createTags(props, { perPage })```

This seemed to have worked out fine. All pages with tags created in WordPress show up nicely in a wordcloud I created in WordPress which creates an index for each tag and the posts associated with it. And the links all work.

If you'd like to see the code for yourself, it is at https://github.com/stevewil/starter.git (version02).

Here is my issue: I want to render each post's tags something like Categories are now rendered on each post.

When I went into /src/templates/types/posts.js I noticed this line:
```<PostCategories categories={categories} />```

So using the method I used previously with Categories, I added an additional line like this:
```<PostTags tags={tags} />```

I also added this line near the top:
```import PostTags from "../../components/PostTags"```

And I added *tags* to the const:
```
const {
    title,
    content,
    featuredImage,
    categories,
    tags,
    excerpt,
    databaseId,
    author,
    date,
  } = page
 ``` 
After saving and re-running *gatsby develop*, Categories render what they are supposed to, but Tags do not. Tags seem to be rendering nothing:
https://stevewil.tinytake.com/tt/NTIyOTM0Ml8xNjM1NDYyOA

I'm wondering if you might have any insight into how I can render tags on posts?

**Comment by henrikwirth** [comment]
Hi @stevewil, glad this repository could give you a good head start.

Not sure when I'll find the time for it. Currently I'm pretty busy, but will let you know the next time I'll update this repo to the newest versions.

**Comment by henrikwirth** [comment]
@stevewil could you figure this out? Do you still need help with this?

**Comment by stevewil** [comment]
Honestly, Henrik, I got involved with my son's lua intro project and it is
consuming all my time.

I really appreciate your efforts to extend Wordpress into a nice Gatsby
front end.

And I am very curious about your research results in comparing WP in php
state with Gatsby.

**Comment by henrikwirth** [comment]
@stevewil no worries. I never got the time to write up an article about my research. But since this stack is developing so fast, I think the numbers in there won't be too relevant anymore. Maybe I still will sum it up at some point, let's see.

I'll close this issue for now. Let me know if you want it reopened once you find the time for it again and if it is still an issue.
