### ISSUE TITLE
WordPress submenu item not showing

### ISSUE THREAD

**Issue by themeplugs** [henrikwirth/gatsby-starter-wordpress-twenty-twenty#28]
Please add a submenu function as soon as possible & how can I added a social share button in blog post.
For Google AdSense how it will work with this stater.

thanks

**Comment by henrikwirth** [comment]
What should I add **as soon as possible**?

I'm happy to accept PRs if you want to add any missing or default functionality. The original twenty twenty theme doesn't seem to have those functions therefore I won't add them to this starter. 

If you need additional functionality I would start at looking at Gatsby plugins https://www.gatsbyjs.com/plugins/?=google

And probably the docs for Gatsby itself to get started with this kind of stack: https://www.gatsbyjs.com/docs/
