### ISSUE TITLE
Thanks for this, possible fixes/improvements

### ISSUE THREAD

**Issue by m-muhsin** [henrikwirth/gatsby-starter-wordpress-twenty-twenty#3]
Hello Henrik,

Thanks for this awesome starter! I checked out the project, and here are some possible fixes/improvements:

- [x] TypeError: Cannot read property 'allWpPost' of undefined. in createCategories.js:40 - occurs when a category does not have any posts in it

- [x] encoding issues - the title of my WP site is `Muhammad's Personal/Tech Blog
About` but in the Gatsby version it occurs as `Muhammad&#039;s Personal/Tech Blog`. Also present in post titles.

- [x] hardcoded WP links can be replaced to their Gatsby counterparts (if possible)

Again, thanks for all your hard work on this! Cheers ✌️

**Comment by henrikwirth** [comment]
1. For the TypeError. This can occur for UnionTypes. In this case there is empty objects and the second query doesn't get any databaseID. Thats why data is undefined. To make sure it doesn't query unnecessary I introduced this line:
https://github.com/henrikwirth/gatsby-starter-wordpress-twenty-twenty/blob/f63f4c47fd363157c3a6040cf0759446c077cb2c/create/createCategories.js#L29

2. The encoding issue is a bit tricky. Not sure if this should be possible to come from the WP site. In another project I use something like: htmlDecoder.decode(title), which uses: https://github.com/mathiasbynens/he
That seems like overhead though for the frontend. I'd prefer to get it done either on page built maybe with resolvers or on WP level. @TylerBarnes maybe you have an idea about this?

3. Yeah thats WIP :)

**Comment by TylerBarnes** [comment]
@henrikwirth yep, we can do that in resolvers. I'll add that to the list for the `gatsby-wordpress-html` plugin.
