### ISSUE TITLE
gatsby-source-wordpress error

### ISSUE THREAD

**Issue by michellejanosi** [henrikwirth/gatsby-starter-wordpress-twenty-twenty#6]
When running `gatsby-develop`, this error is received:

 ERROR 

 gatsby-source-wordpress  The "url" argument must be of type string. Received null

GraphQL request to null failed.

Please ensure the following statements are true
  - your WordPress URL is correct in gatsby-config.js
  - your server is responding to requests
  - WPGraphQL and WPGatsby are installed in your WordPress backend

**Comment by henrikwirth** [comment]
Hi @michellejanosi I added another point in the Readme about the `.env` file:

4. Rename `.env.example` file to `.env` and edit it with your domain variables.


Please make sure your domains are entered there correctly and try again. Hope that helps ✌️
